name: Update AFL Stats
on:
  schedule:
    # Run every hour during AFL game days (typically Thursday-Sunday)
    - cron: '10 * * * 4,5,6,0'  # Every hour at 10 minutes past, on Thursday(4), Friday(5), Saturday(6), Sunday(0)
  workflow_dispatch:  # Allow manual trigger for testing
    inputs:
      game_id:
        description: 'Specific game ID to update (leave empty to check all scheduled games)'
        required: false
        default: ''

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd src/app/scripts
          npm ci || npm install

      - name: Create .env file
        run: |
          cd src/app/scripts
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
          
      - name: Run stats update script
        id: update-script
        run: |
          cd src/app/scripts
          # Run script with specific game_id if provided
          if [ -n "${{ github.event.inputs.game_id }}" ]; then
            node update-afl-stats.js ${{ github.event.inputs.game_id }}
          else
            node update-afl-stats.js
          fi
          # Set output variable based on script output
          if grep -q "PROCESSED_FIXTURES=true" <<< "$(cat /tmp/script_output.txt)"; then
            echo "CHANGES_MADE=true" >> $GITHUB_OUTPUT
          else
            echo "CHANGES_MADE=false" >> $GITHUB_OUTPUT
          fi
        
      - name: Commit changes if fixtures were updated
        if: steps.update-script.outputs.CHANGES_MADE == 'true'
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add src/app/scripts/processed-games.json
          git commit -m "Update processed games record [skip ci]"
          git push