name: Update AFL Fixtures

on:
  schedule:
    # Melbourne EST times (UTC+10/11 depending on daylight savings)
    # For simplicity, assuming UTC+10 (so subtract 10 hours for UTC time)
    - cron: '00 21 * * 1'   # 7:00 AM Tuesday in Melbourne (21:00 UTC Monday)
    - cron: '00 21 * * 2'   # 7:00 AM Wednesday in Melbourne (21:00 UTC Tuesday)
    - cron: '00 21 * * 3'   # 7:00 AM Thursday in Melbourne (21:00 UTC Wednesday)
    - cron: '30 13 * * 4'   # 11:00 PM Thursday in Melbourne (13:00 UTC)
    - cron: '00 13 * * 5'   # 11:00 PM Friday in Melbourne (13:00 UTC)
    - cron: '30 9 * * 6'    # 7:30 PM Saturday in Melbourne (9:30 UTC)
    - cron: '30 13 * * 6'   # 11:00 PM Saturday in Melbourne (13:00 UTC)
    - cron: '00 8 * * 0'    # 6:00 PM Sunday in Melbourne (8:00 UTC)
    - cron: '30 13 * * 0'   # 11:00 PM Sunday in Melbourne (13:00 UTC)
    - cron: '00 8 * * 1'    # 6:00 PM Monday in Melbourne (8:00 UTC)
    - cron: '30 13 * * 1'   # 11:00 PM Monday in Melbourne (13:00 UTC)
  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  update-fixtures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to avoid shallow clone issues
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: cd src/app/scripts && npm install
      
      - name: Update fixtures
        run: cd src/app/scripts && node download-fixtures.js
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          # Add all changes first
          git add .
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update AFL fixtures"
            # Pull with rebase (after committing)
            git pull --rebase origin main
            git push
          fi
