name: Update AFL Stats
on:
  schedule:
    # Run every hour during AFL game days (typically Thursday-Sunday)
    - cron: '0 * * * 4,5,6,0'  # Every hour on Thursday(4), Friday(5), Saturday(6), Sunday(0)
  workflow_dispatch:  # Allow manual trigger for testing
    inputs:
      game_id:
        description: 'Specific game ID to update (leave empty to check all scheduled games)'
        required: false
        default: ''

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd src/app/scripts
          npm install
          npm install cheerio axios mongodb dotenv

      - name: Create .env file
        run: |
          cd src/app/scripts
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
          
      - name: Run stats update script
        run: |
          cd src/app/scripts
          node update-afl-stats.js ${{ github.event.inputs.game_id }}
        
      - name: Commit changes if fixtures were updated
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add src/app/scripts/processed-games.json || true
          git diff --quiet && git diff --staged --quiet || git commit -m "Update processed games record"
          git push
